name: Run tests

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        versions: [ '8.2', '8.3', '8.4' ]
    name: PHP ${{ matrix.versions }} Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.versions }}
          extensions: dom, curl, libxml, openssl, fileinfo, json, xml, mbstring, zip, pcntl, pdo, gettext, sqlite3, mysqli, pgsql, pdo_sqlite, pdo_mysql, pdo_pgsql, bcmath, soap, intl, gd, exif, iconv, date, sockets, session, tokenizer, ctype, filter, hash, pcre
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-progress --no-interaction --prefer-dist

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
            bun-version: latest

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest

      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan storage:link
          php artisan migrate
          php artisan db:seed
          php artisan clear:config
          bun install
          bun run build

      - name: Run tests
        run: php artisan test
